version: '3'

services:
  web:
    build: .
    ports:
     - "80:80"
  mysql:
    image: mysql:5.5
    restart: always
    environment:
      MYSQL_DATABASE: wwasave
      MYSQL_ROOT_PASSWORD: example